---
- name: Add and enable Brave Browser repo (Fedora)
  command:
    cmd: "dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/"
    warn: false
    creates: "/etc/yum.repos.d/brave-browser-rpm-release.s3.brave.com_x86_64_.repo"
  when: |
    install_brave and
    ansible_facts['distribution'] == "Fedora"
  become: yes

- name: Add Brave Browser RPM key (Fedora)
  rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  when: |
    install_brave and
    ansible_facts['distribution'] == "Fedora"
  become: yes

- name: Install Brave Browser
  package:
    name: brave-browser
    state: present
  when: install_brave and ansible_facts['distribution'] != "Alpine"
  become: yes
