---
- name: Add and enable Brave Browser repo (Fedora)
  command:
    cmd: "dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/"
    warn: false
    creates: "/etc/yum.repos.d/brave-browser-rpm-release.s3.brave.com_x86_64_.repo"
  when: |
    install_brave and
    ansible_facts['distribution'] == "Fedora"
  become: true

- name: Add Brave Browser RPM key (Fedora)
  rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  when: ansible_facts['distribution'] == "Fedora"
  become: true

- name: Install prerequisites for Brave Browser (Debian)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - curl
    - gnupg
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Add apt key for the Brave Browser repository (Debian)
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present

- name: Add Brave Browser repository (Debian)
  ansible.builtin.apt_repository:
    repo: deb https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
    filename: brave-browser-release
    update_cache: true

- name: Install Brave Browser
  package:
    name: brave-browser
    state: present
  when: install_brave and ansible_facts['distribution'] != "Alpine"
  become: true
