---
- name: Install Chromium
  package:
    name: chromium
    state: present
  become: true
  when: |
    ansible_facts['distribution'] == "Alpine" or
    ansible_facts['os_family'] == "Fedora"

- debug:
    msg: |
      Sorry, Chromium is having some issues on Debian -
      install from Flatpak or Snap
  when:
    ansible_facts['distribution'] == "Debian"

- name: Install Chromium
  package:
    name: chromium-browser
    state: present
  become: true
  when: |
    ansible_facts['distribution'] == "Pop!_OS" or
    ansible_facts['distribution'] == "Ubuntu"
