---
# tasks file for ansible-role-packages
- name: Update cache for Debian-based distros
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  changed_when: false
  become: true

- name: Update cache for Alpine
  apk:
    update_cache: yes
  when: ansible_facts['distribution'] == 'Alpine'
  changed_when: false
  become: true

- name: Make sure dnf-plugins-core are installed (Fedora)
  package:
    name: dnf-plugins-core
    state: present
  become: true
  when: ansible_facts['distribution'] == "Fedora"

- name: Include rpm-fusion repositories
  include_tasks: rpmfusion.yml
  when: |
    ansible_facts['distribution'] == "Fedora" and
    install_rpmfusion is defined and install_rpmfusion

- name: Include system packages to install
  include_tasks: pkg.yml

- name: Include flatpak packages to install
  include_tasks: flatpak.yml
  when: not ci_test|default(false)

- name: Include pip packages to install
  include_tasks: pip.yml
  when: (pip_packages | length) > 0

- name: Include go packages to install
  include_tasks: go.yml
  when: (go_packages | length) > 0

- name: Include cargo packages to install
  include_tasks: cargo.yml
  when: (cargo_packages | length) > 0

- name: Include npm and yarn packages to install
  include_tasks: js.yaml
  when: |
    (npm_packages | length) > 0 or
    (yarn_packages | length) > 0

- name: Include the brave browser installation
  include_tasks: brave.yml
  when: |
    install_brave is defined and install_brave and
    ansible_facts['os_family'] != "Alpine"

- name: Include the firefox browser installation
  include_tasks: firefox.yml
  when: install_firefox is defined and install_firefox

- name: Include the chromium browser installation
  include_tasks: chromium.yml
  when: install_chromium is defined and install_chromium

- name: Include the chrome browser installation
  include_tasks: chrome.yml
  when: |
    install_chrome is defined and install_chrome and
    ansible_facts['os_family'] != "Alpine"
