---
- name: Install rpm-fusion free
  command:
    cmd: "dnf install {{ rpmfusion_repos.free }} -y"
  changed_when: false
  become: true
  when: |
    install_rpmfusion.free is defined and
    install_rpmfusion.free or
    (install_rpmfusion.both is defined and not install_rpmfusion.both)

- name: Install rpm-fusion nonfree
  command:
    cmd: "dnf install {{ rpmfusion_repos.nonfree }} -y"
  changed_when: false
  become: true
  when: |
    install_rpmfusion.nonfree is defined and
    install_rpmfusion.nonfree or
    (install_rpmfusion.both is defined and not install_rpmfusion.both)

- name: Install both free and nonfree rpm-fusion
  command:
    cmd: "dnf install {{ rpmfusion_repos.free }} {{ rpmfusion_repos.nonfree }} -y"
  changed_when: false
  become: true
  when: |
    install_rpmfusion.both is defined and
    install_rpmfusion.both
